In [1]:
# Load libraries
import pandas as pd
import numpy as np
import h5py
import utils


In [2]:
# Load the dataset
df = pd.read_csv('../../data/BindingDB_IC50_updated.csv')
print(df.shape)
df.head()


(18815, 21)


BindingDB Ligand Name ChEMBL ID of Ligand  \
0  (2S)-1-[(2S,4R)-4-benzyl-2-hydroxy-4-{[(1S,2R)...           CHEMBL115   
1  (2S)-N-[(2S,3R)-4-[(3S,4aS,8aS)-3-(tert-butylc...           CHEMBL114   
2  (3S)-oxolan-3-yl N-[(2S,3R)-4-[(4-aminobenzene...           CHEMBL116   
3  (2S)-N-[(2S,3R)-4-[(3S,4aS,8aS)-3-(tert-butylc...           CHEMBL114   
4  (2S,3R,4R,6R)-3-methoxy-2-methyl-4-(methylamin...        CHEMBL388978   

  DrugBank ID of Ligand ZINC ID of Ligand  \
0                   NaN      ZINC22448696   
1                   NaN      ZINC03914596   
2                   NaN      ZINC03809192   
3                   NaN      ZINC03914596   
4                   NaN      ZINC03814434   

                                       Ligand SMILES  \
0  CC(C)(C)NC(=O)[C@@H]1CN(Cc2cccnc2)CCN1C[C@@H](...   
1  CC(C)(C)NC(=O)[C@@H]1C[C@@H]2CCCC[C@@H]2CN1C[C...   
2  CC(C)CN(C[C@@H](O)[C@H](Cc1ccccc1)NC(=O)O[C@H]...   
3  CC(C)(C)NC(=O)[C@@H]1C[C@@H]2CCCC[C@@H]2CN1C[C...   
4  CN[C@@H]1C[C@H]2O[C@@](C)([C@@H]1OC)n1c3ccccc3...   

                              Target Name  \
0  Dimer of Gag-Pol polyprotein [501-599]   
1  Dimer of Gag-Pol polyprotein [489-587]   
2  Dimer of Gag-Pol polyprotein [489-587]   
3  Dimer of Gag-Pol polyprotein [489-587]   
4              Protein kinase C beta type   

                     BindingDB Target Chain Sequence  \
0  PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMSLPGRWKPKM...   
1  PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKM...   
2  PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKM...   
3  PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKM...   
4  MADPAAGPPPSEGEESTVRFARKGALRQKNVHEVKNHKFTARFFKQ...   

                         Link to Ligand in BindingDB  \
0  http://www.bindingdb.org/bind/chemsearch/marvi...   
1  http://www.bindingdb.org/bind/chemsearch/marvi...   
2  http://www.bindingdb.org/bind/chemsearch/marvi...   
3  http://www.bindingdb.org/bind/chemsearch/marvi...   
4  http://www.bindingdb.org/bind/chemsearch/marvi...   

                         Link to Target in BindingDB  \
0  http://www.bindingdb.org/jsp/dbsearch/PrimaryS...   
1  http://www.bindingdb.org/jsp/dbsearch/PrimaryS...   
2  http://www.bindingdb.org/jsp/dbsearch/PrimaryS...   
3  http://www.bindingdb.org/jsp/dbsearch/PrimaryS...   
4  http://www.bindingdb.org/jsp/dbsearch/PrimaryS...   

             Link to Ligand-Target Pair in BindingDB  ...  \
0  http://www.bindingdb.org/jsp/dbsearch/PrimaryS...  ...   
1  http://www.bindingdb.org/jsp/dbsearch/PrimaryS...  ...   
2  http://www.bindingdb.org/jsp/dbsearch/PrimaryS...  ...   
3  http://www.bindingdb.org/jsp/dbsearch/PrimaryS...  ...   
4  http://www.bindingdb.org/jsp/dbsearch/PrimaryS...  ...   

  Target Source Organism According to Curator or DataSource IC50 (nM)  \
0                     Human immunodeficiency virus 1             0.36   
1                     Human immunodeficiency virus 1             8.40   
2                     Human immunodeficiency virus 1             2.60   
3                     Human immunodeficiency virus 1            11.20   
4                                  Rattus norvegicus             9.00   

         pert_id      cmap_name  target                     moa  \
0  BRD-K33226500      indinavir  CYP3A7  HIV protease inhibitor   
1  BRD-K09963420     saquinavir     NaN                     NaN   
2  BRD-K47827687     amprenavir     NaN                     NaN   
3  BRD-K09963420     saquinavir     NaN                     NaN   
4  BRD-K17953061  staurosporine    CDK2           PKC inhibitor   

                                    canonical_smiles  \
0  CC(C)(C)NC(=O)[C@@H]1CN(Cc2cccnc2)CCN1C[C@@H](...   
1  CC(C)(C)NC(=O)[C@@H]1C[C@@H]2CCCC[C@@H]2CN1C[C...   
2  CC(C)CN(C[C@@H](O)[C@H](Cc1ccccc1)NC(=O)O[C@H]...   
3  CC(C)(C)NC(=O)[C@@H]1C[C@@H]2CCCC[C@@H]2CN1C[C...   
4  CN[C@@H]1C[C@H]2O[C@@](C)([C@@H]1OC)n3c4ccccc4...   

                     inchi_key compound_aliases  \
0  CBVCZFGXHXORBI-PXQQMZJSSA-N              NaN   
1  QWAXKHKRTORLEM-UGJKXSETSA-N      

In [3]:
# Segregate drugs, proteins and labels
df_drugs = df['Ligand SMILES']
df_proteins = df['BindingDB Target Chain Sequence']
df_labels = df['IC50 (nM)']

In [4]:
# Preprocess drugs
df_drugs

0        CC(C)(C)NC(=O)[C@@H]1CN(Cc2cccnc2)CCN1C[C@@H](...
1        CC(C)(C)NC(=O)[C@@H]1C[C@@H]2CCCC[C@@H]2CN1C[C...
2        CC(C)CN(C[C@@H](O)[C@H](Cc1ccccc1)NC(=O)O[C@H]...
3        CC(C)(C)NC(=O)[C@@H]1C[C@@H]2CCCC[C@@H]2CN1C[C...
4        CN[C@@H]1C[C@H]2O[C@@](C)([C@@H]1OC)n1c3ccccc3...
                               ...                        
18810              O=C(CCCCCN1C(=O)c2cccc3cccc(c23)C1=O)NO
18811           Nc1ccccc1NC(=O)c1ccc(CNC(=O)OCc2cccnc2)cc1
18812                          O=C(CCCCCCC(=O)Nc1ccccc1)NO
18813              O=C(CCCCCN1C(=O)c2cccc3cccc(c23)C1=O)NO
18814           Nc1ccccc1NC(=O)c1ccc(CNC(=O)OCc2cccnc2)cc1
Name: Ligand SMILES, Length: 18815, dtype: object

In [5]:
# One-hot encoding of drug SMILES

S = pd.Series(df_drugs.unique()).apply(utils.smiles2onehot)
S_dict = dict(zip(df_drugs.unique(), S))
df_drugs = [S_dict[i] for i in df_drugs]

In [6]:
one_hot_drugs = np.array(df_drugs)
one_hot_drugs.shape

(18815, 277, 76)

In [7]:
one_hot_drugs

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0.

In [8]:
# Preprocess proteins
df_proteins

0        PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMSLPGRWKPKM...
1        PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKM...
2        PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKM...
3        PQITLWQRPLVTIKIGGQLKEALLDTGADDTVLEEMNLPGRWKPKM...
4        MADPAAGPPPSEGEESTVRFARKGALRQKNVHEVKNHKFTARFFKQ...
                               ...                        
18810    MHSMISSVDVKSEVPVGLEPISPLDLRTDLRMMMPVVDPVVREKQL...
18811    MHSMISSVDVKSEVPVGLEPISPLDLRTDLRMMMPVVDPVVREKQL...
18812    MGTALVYHEDMTATRLLWDDPECEIERPERLTAALDRLRQRGLEQR...
18813    MGTALVYHEDMTATRLLWDDPECEIERPERLTAALDRLRQRGLEQR...
18814    MGTALVYHEDMTATRLLWDDPECEIERPERLTAALDRLRQRGLEQR...
Name: BindingDB Target Chain Sequence, Length: 18815, dtype: object

In [9]:
# Tokenize amino acid sequences

AA = pd.Series(df_proteins.unique()).apply(utils.protein2onehot)
AA_dict = dict(zip(df_proteins.unique(), AA))
df_proteins = [AA_dict[i] for i in df_proteins]

In [10]:
one_hot_proteins = np.array(df_proteins)
one_hot_proteins.shape

(18815, 26, 1000)

In [11]:
one_hot_proteins

array([[[0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [12]:
# Preprocess labels
df_labels

0             0.36
1             8.40
2             2.60
3            11.20
4             9.00
           ...    
18810       700.00
18811    100000.00
18812       200.00
18813       300.00
18814     11100.00
Name: IC50 (nM), Length: 18815, dtype: float64

In [13]:
# Transform labels

L_dict = pd.Series(df_labels)
l_converted = L_dict.apply(lambda l: utils.convert_y_unit(l, from_='nM', to_='p')).tolist()
np.shape(l_converted)

(18815,)

In [14]:
l_converted

[9.443697499232712,
 8.075720713938118,
 8.585026652029182,
 7.950781977329818,
 8.045757490560675,
 6.259637310505756,
 4.928117992693875,
 4.3979400086720375,
 7.0,
 5.698970004336019,
 5.494850021680094,
 4.0,
 8.0,
 5.698970004336019,
 6.154901959985743,
 8.045757490560675,
 6.91721462968355,
 8.221848749616356,
 7.522878745280337,
 5.853871964321762,
 4.0,
 8.0,
 8.045757490560675,
 7.3979400086720375,
 7.7447274948966935,
 6.3979400086720375,
 8.0,
 6.045757490560675,
 6.494850021680094,
 9.508638306165727,
 11.096910013008056,
 11.096910013008056,
 11.096910013008056,
 6.522878745280337,
 6.221848749616356,
 6.431798275933005,
 6.3979400086720375,
 2.9030899869919438,
 3.337242168318426,
 3.3467874862246565,
 4.455931955649724,
 5.522878745280337,
 5.619788758288394,
 6.045757490560675,
 7.795880017344075,
 7.154901959985743,
 8.920818753952375,
 8.698970004336019,
 6.943095148663527,
 5.698970004336019,
 7.0,
 5.154901959985743,
 5.795880017344075,
 7.3979400086720375,
 5.44369

In [15]:
# Save drug encodings

h5f = h5py.File('../../data/drugs.h5', 'w')
h5f.create_dataset('data', data=one_hot_drugs)
h5f.close()


In [16]:
h5f = h5py.File('../../data/drugs.h5', 'r')
data = h5f['data'][:]
h5f.close()

data

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0.

In [17]:
# Save protein encodings

h5f = h5py.File('../../data/proteins.h5', 'w')
h5f.create_dataset('data', data=one_hot_proteins)
h5f.close()


In [18]:
h5f = h5py.File('../../data/proteins.h5', 'r')
data = h5f['data'][:]
h5f.close()

data

array([[[0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [19]:
# Save labels

h5f = h5py.File('../../data/pIC50.h5', 'w')
h5f.create_dataset('data', data=l_converted)
h5f.close()


In [20]:
h5f = h5py.File('../../data/pIC50.h5', 'r')
data = h5f['data'][:]
h5f.close()

data

array([9.4436975 , 8.07572071, 8.58502665, ..., 6.69897   , 6.52287875,
       4.95467702])

In [21]:
# Done